//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SbirkaPrikladuEU {
    
    
    public partial class Default {
        
        /// <summary>
        /// groupMenuUC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SbirkaPrikladuEU.Class.groupMenu groupMenuUC;
        
        /// <summary>
        /// pf2013Tag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pf2013Tag;
        
        /// <summary>
        /// topHeroUnitTag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl topHeroUnitTag;
        
        /// <summary>
        /// exampleFilterUC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SbirkaPrikladuEU.Class.filter exampleFilterUC;
        
        /// <summary>
        /// examplesFromGroupIdUC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SbirkaPrikladuEU.Class.examplesFromGroupId examplesFromGroupIdUC;
        
        /// <summary>
        /// lastInsertedExamplesUC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SbirkaPrikladuEU.Class.lastInsertedExamples lastInsertedExamplesUC;
    }
}
